### ISSUE TITLE
Moving Objects

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/FlappyBird#3]
Spawn pipes that move across the screen. Once the pipes are not seen by the player delete the game object. Apply rectangle collider on the pipe and set to trigger.

*Recommended to use Rigidbody or edit transform.position. Make sure the pipes move relative to the game speed than the frame rate.

**Comment by BrandonPacewic** [comment]
~~@Galaxy25 is this something that you want me to take a crack at? I could then show everyone how it works. Or do you want someone else to work on this as a exercise for learning Unity?~~

**Comment by BrandonPacewic** [comment]
@Galaxy25 any plans to update this repo with the code that you wrote in the examples?
